"""Prompt templates for the investigation layer (Member 2)."""

from __future__ import annotations

from app.agents.prompts.investigation import (
    BEHAVIORAL_ANALYSIS_PROMPT,
    BUSINESS_CONTEXT_PROMPT,
    DETERMINISTIC_SUMMARY_TEMPLATE,
    EVIDENCE_SYNTHESIS_PROMPT,
    GUARDRAIL_PREAMBLE,
    HANDOFF_SUMMARY_PROMPT,
    RECOMMENDATION_PROMPT,
    RELATIONSHIP_ANALYSIS_PROMPT,
)

__all__ = [
    "BEHAVIORAL_ANALYSIS_PROMPT",
    "BUSINESS_CONTEXT_PROMPT",
    "DETERMINISTIC_SUMMARY_TEMPLATE",
    "EVIDENCE_SYNTHESIS_PROMPT",
    "GUARDRAIL_PREAMBLE",
    "HANDOFF_SUMMARY_PROMPT",
    "RECOMMENDATION_PROMPT",
    "RELATIONSHIP_ANALYSIS_PROMPT",
]
